<div class="home-herobanner">
	<img src="<?php echo $this->getViewFileUrl('images/home-herobanner.jpg'); ?>" alt="Blink Easy Shopping" />
</div>

<div class="custom-inner-container">
	<div class="about-blink-sect inner-content">
		<h2 class="page-title">About Blink</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</div>

<div class="custom-inner-container">
	<div class="affiliate-sect inner-content">
		<h2 class="page-title">Affiliates At A Glance</h2>
		<ul>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo1.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo2.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo3.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo4.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo5.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo6.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo7.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo8.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo9.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo10.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo11.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo12.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo13.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo14.png'); ?>" alt="" /></a></li>
			<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/affiliate-logo15.png'); ?>" alt="" /></a></li>
		</ul>
	</div>
</div>